services:
  - type: web
    name: deepfake-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements_clean.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.10






